allowBuilds:
  '@firebase/util': true
  '@google/genai': true
  esbuild: true
  protobufjs: true
minimumReleaseAgeExclude:
  - '@vercel/build-utils@13.33.0'
  - '@vercel/node@5.8.24'
  - '@capacitor/android@8.4.2 || 8.5.1'
  - '@capacitor/app@8.1.1'
  - '@capacitor/cli@8.4.2 || 8.5.1'
  - '@capacitor/core@8.4.2 || 8.5.1'
  - '@capacitor/status-bar@8.0.3'
  - autoprefixer@10.5.3
  - '@google/genai@2.20.0'
